class_name PackRatDemoPack extends RefCounted
## One downloadable PackRat Portal showcase pack.

## Stable cache ID used for this pack.
var id: String = ""

## User-facing pack title.
var title: String = ""

## Short 2-4 word user-facing description of the pack's content.
var summary: String = ""

## Pack format label, usually PCK or ZIP.
var format: String = ""

## Release asset and mirrored static-host filename.
var file_name: String = ""

## Scene path exposed after the pack is mounted.
var entry_path: String = ""

## Expected remote file size generated by the demo pack builder.
var expected_size: int = 0

## Expected modified time generated by the demo pack builder when available.
var expected_modified_time: int = 0

## Generated content token used to avoid stale HTTP and PackRat cache hits.
var version_token: String = ""

## Card accent color.
var accent_color: Color = Color.WHITE


## Creates a complete immutable pack descriptor for the demo catalog.
static func create(
	pack_id: String,
	pack_title: String,
	pack_summary: String,
	pack_format: String,
	pack_file_name: String,
	pack_entry_path: String,
	pack_expected_size: int,
	pack_expected_modified_time: int,
	pack_version_token: String,
	pack_accent_color: Color
) -> PackRatDemoPack:
	var pack: PackRatDemoPack = PackRatDemoPack.new()
	pack.id = pack_id
	pack.title = pack_title
	pack.summary = pack_summary
	pack.format = pack_format
	pack.file_name = pack_file_name
	pack.entry_path = pack_entry_path
	pack.expected_size = pack_expected_size
	pack.expected_modified_time = pack_expected_modified_time
	pack.version_token = pack_version_token
	pack.accent_color = pack_accent_color
	return pack


## Returns this pack's static-host URL.
func pages_url() -> String:
	return _versioned_url(PackRat.join_url(PackRatDemoCatalog.pages_pack_base_url, file_name))


## Returns this pack's GitHub Release URL.
func github_release_url() -> String:
	return _versioned_url(PackRat.github_release_url(
		PackRatDemoCatalog.RELEASE_OWNER,
		PackRatDemoCatalog.RELEASE_REPO,
		file_name,
		PackRatDemoCatalog.release_tag
	))


## Returns this pack's URL for [param source].
func url_for_source(source: String) -> String:
	if source == PackRatDemoCatalog.SOURCE_GITHUB_RELEASE:
		return github_release_url()

	return pages_url()


## Builds PackRat options for this pack.
func options() -> PackRatOptions:
	var pack_options: PackRatOptions = PackRatOptions.new()
	pack_options.id = _cache_id()
	pack_options.entry_path = entry_path
	pack_options.replace_files = false
	pack_options.expected_size = expected_size
	pack_options.expected_modified_time = expected_modified_time
	pack_options.capture_timings = true
	return pack_options


func _versioned_url(url: String) -> String:
	if version_token.is_empty():
		return url

	var separator: String = "?" if not url.contains("?") else "&"
	return "%s%sv=%s" % [url, separator, version_token.uri_encode()]


func _cache_id() -> String:
	if version_token.is_empty():
		return id

	return "%s-%s" % [id, version_token]
